### ISSUE TITLE
[bug] custom remote SSH port does not work

### ISSUE THREAD

**Issue by brosky** [aker-gateway/Aker#91] opened 2019-04-17 07:49 UTC
Hi, 

I have a console appliance that via SSH on port 22 gives administration menu and on port 7000 gives user menu. 

Setting a custom port in hosts.json connects to port 22 instead of 7000

My config: 

{ "name": "Console",       "hostname": "1.2.3.4",      "port": "7000", "key": "~/.ssh/id_rsa", "usergroups": [ "lnxadmins" ], hostgroups": [ "linuxservers" ] },

Log: 

Apr 17 10:42:58 sshgw-cj systemd-logind: New session 28624 of user brosky.
Apr 17 10:42:59 sshgw-cj Aker: aker INFO - Core: Starting up, user=aker from=1.2.3.254:60319
Apr 17 10:42:59 sshgw-cj Aker: IdPFactory INFO - IdPFactory: trying dynamic loading of module : Json
Apr 17 10:42:59 sshgw-cj Aker: Json INFO - Json: loaded
Apr 17 10:42:59 sshgw-cj Aker: hosts INFO - Hosts: loading hosts from cache
Apr 17 10:43:00 sshgw-cj Aker: tui INFO - TUI: Refreshing entries for user brosky
Apr 17 10:43:00 sshgw-cj Aker: aker INFO - Core: reloading hosts for user brosky from backened identity provider
Apr 17 10:43:01 sshgw-cj systemd: Started Session 28625 of user root.
Apr 17 10:43:02 sshgw-cj Aker: tui INFO - TUI: Refreshing entries for user brosky
Apr 17 10:43:02 sshgw-cj Aker: aker INFO - Core: reloading hosts for user brosky from backened identity provider
Apr 17 10:43:05 sshgw-cj Aker: aker INFO - Core: Starting session UUID fc075808-5cc4-4004-966a-b6bd35cf7c3d for user brosky to host 1.2.3.4
Apr 17 10:43:05 sshgw-cj Aker: transport INFO - Connected (version 2.0, client OpenSSH_4.2)
Apr 17 10:43:06 sshgw-cj Aker: transport INFO - Authentication (publickey) failed.
Apr 17 10:43:10 sshgw-cj Aker: transport INFO - Authentication (password) successful!

I've tried this with different hosts and it seems to always use port 22 - tcpdump on the outgoing interface shows nothing.

**Comment by anazmy** [comment] 2019-04-20 03:15
Yeah, that is a duplicate of #38 
I think it can be applied with recent changes now.

**Comment by jgraham-bw** [comment] 2020-05-22 00:26
Having the same issue for a server using port 2024. Tshark capture showing that despite the hosts.json file configured for port 2024, it ssh's to port 22.

**Comment by anazmy** [comment] 2020-05-22 13:20
@jgraham-bw you're using JSON provider, right?

**Comment by anazmy** [comment] 2020-05-22 13:24
@jgraham-bw @brosky 

For JSON provider, ssh custom port should work now, can you please test and let me know your feedback?

**Comment by jgraham-bw** [comment] 2020-05-22 15:29
Thank you for the quick reply. Pulled the new code, but getting a traceback error now. Formatting was bad here, attached traceback.
[aker_port_traceback.txt](https://github.com/aker-gateway/Aker/files/4668994/aker_port_traceback.txt)

**Comment by anazmy** [comment] 2020-05-22 15:33
Most probably you have the old json file format. The change is simple, please change port to ssh_port in the json file and retry.

**Comment by jgraham-bw** [comment] 2020-05-22 15:37
Yep, that was the problem. Thank you very much!!! Custom port issue is fixed.

**Comment by anazmy** [comment] 2020-05-22 16:35
Thanks for confirming

**Closed as completed by anazmy** 2020-05-22 16:35 UTC
