### ISSUE TITLE
Hostname probleme,port probleme

### ISSUE THREAD

**Issue by botti007** [aker-gateway/Aker#66] opened 2018-02-23 10:23 UTC
hello , 
actually i had two problemes the first : your connect methode point on the name key of host json 
however in my case i want that ssh connect method point on hostname because i want in json file make : NAME:firweallcli
hostname: IP of firewall 

second probleme all serveur must be initiate on port 22 and this is not my case because i had servers that are initiate in port 22 and the other no so whene i edit json file nothing change "always probleme of port"

in you'r code `` def __init__(self, name, memberof_hostgroups, ssh_port=22):
        self.fqdn = name
        self.name = name
        self.ssh_port = ssh_port
        self.hostgroups = memberof_hostgroups``

you are initiate you'r port always on 22 

so please help me to make aker point on the port that i give it json file 
and also help me to maker aker point on hostname that i give it in json file not the name 

i hope you help me please

**Comment by anazmy** [comment] 2018-02-27 17:35
Hi @botti007 

Yes that was mentioned earlier on issue #38 , should be handled in a future version

**Comment by anazmy** [comment] 2018-02-27 17:35
Closing as duplicate of #38

**Closed as completed by anazmy** 2018-02-27 17:35 UTC
